### ISSUE TITLE
As a player, I want my current fate points and initiative status to be saved in my character sheet in case I disconnect from a game

### ISSUE THREAD

**Issue by player-03** [fariapp/fari#106]
## 🚩 The problem

My group is having trouble with disconnecting. Even though we're geographically nearby and I (the host) have pretty good internet, a player disconnects at least every 20 minutes. Rejoining is easy, but the problem is, their fate points reset to 3, their turn status resets to "hasn't gone yet," and their last die roll is blank.

Individually, it isn't hard to remember any of these things, but they add up over time.

## ✅ My preferred solution

When a player disconnects, their character should remain in the sidebar. Grey it out a bit, show a button for the GM to remove the character, and otherwise make it behave like the characters in an offline game.

When someone joins, if their character name matches a greyed-out character, they take control of that character, keeping the existing fate points, turn status, and dice roll.

## ✏️ Alternatives and future improvements

- It would be nice if the connection was more stable, but that's hard to implement, and no matter how well you do it it's impossible to guarantee stability.
- Instead of only preserving the characters for the current session, you could save them to the scene itself. Not necessarily the whole character sheet, just the three values that get lost. This might be overkill, though.
- Instead of saving everything, you could save fate points to the character sheet. This makes some sense as fate points are supposed to carry over between sessions, and they follow the character rather than the scene. It only solves part of the problem above, but could be useful in its own right.
- In the longer term, my preferred solution opens up the option to merge offline and online games. That is, you'd offer both the "copy game link" and "add character" buttons in online games. Then some players could join directly while others watch through screen sharing.

**Comment by RPDeshaies** [comment]
Hey,

Thanks for opening this issue.

I'll look into connection instability but as you said, there is a lot of factors that can make connections... unreliable.

> When someone joins, if their character name matches a greyed-out character, they take control of that character, keeping the existing fate points, turn status, and dice roll.

The way it's currently configured is that there is the concept of "Players" and "Characters". A Player joins a game with or without their Character. If a player disconnects, the player is then "removed from the list of players along with their Character that they brought to the table". So support this I think I would need to find a way to decouple the current models.

> When someone joins, if their character name matches a greyed-out character, they take control of that character, keeping the existing fate points, turn status, and dice roll.

This seems pretty reasonable to me where fate points, turn state are saved in the character sheet. I'm not too sure about including the dice roll in there though.

> It would be nice if the connection was more stable, but that's hard to implement, and no matter how well you do it it's impossible to guarantee stability.

yeah, 💯  and thanks for understanding :/ I use Fari on a daily basis myself and haven't had connection issues myself but if I discover anything I will always try to fix it. There are reconnection mechanisms under the hood but they don't always work. 

Honestly, if Fari was a paid product, I would probably use and pay for something like Google's Firebase but for now I have to rely on peer to peer connections.

> Instead of only preserving the characters for the current session, you could save them to the scene itself. Not necessarily the whole character sheet, just the three values that get lost. This might be overkill, though.

Technically, Players and their Characters are saved in the Scenes, but removed upon disconnections.

> Instead of saving everything, you could save fate points to the character sheet. 

I think that will be the first try I'm going to try. **Saving Fate Points and Turn Status in the Character sheet**. 

> In the longer term, my preferred solution opens up the option to merge offline and online games

Adding an "Add Character" button to the Online experience would not be too hard I think. I'll think about that as well

**Comment by player-03** [comment]
> The way it's currently configured is that there is the concept of "Players" and "Characters". A Player joins a game with or without their Character. If a player disconnects, the player is then "removed from the list of players along with their Character that they brought to the table". So support this I think I would need to find a way to decouple the current models.

Yeah, that's about what I figured. This is why once a solution is found, it becomes easier to merge offline and online games. Actually...

> Adding an "Add Character" button to the Online experience would not be too hard I think.

In that case you might want to do this backwards.

1. Implement the "add character" button.
2. When someone disconnects, add an NPC to the list with their info, as if the GM clicked "add character."
3. When someone joins, check their character's name against any existing NPCs. If there's an exact match, copy the data and delete that NPC.

Even just steps 1 and 2 would help on their own. Without step 3 (or if step 3 fails due to a name change), the GM can still copy the information over. But having all 3 is ideal to minimize the required effort.

As far as users are concerned, the main difference is that it'll mess with the ordering. Not a huge loss, though.

> I use Fari on a daily basis myself and haven't had connection issues myself

That's the story of web development right there.

**Comment by RPDeshaies** [comment]
So I did some code to save the initiative tracker and the number of fate points on the character object and it looks generally like it won't have too many side effects.

I also added the "add character" button inside the online game page and it looks relatively OK. 

Though I feel like the UI is a bit more "busy". I'll talk to some designer friends of mine to see if they have any inputs on how I could make the UI better to handle that many buttons...

But feature-wise, it should be OK :) 

![image](https://user-images.githubusercontent.com/6224111/92799852-23320480-f382-11ea-8eb0-ea9fe169a211.png)

**Comment by player-03** [comment]
Yay!

You're definitely right that the UI is getting kind of busy. It may be time to rearrange a couple things.

The "add character" button, for instance. It should probably go right above or right below the player list. (Think of the character sheets - every time there's a button to add another of something, it's a big plus shape in the top-right of the section it adds to. That design works; why not make it standard?) I guess the problem is that the "reset initiative" button is taking up that space.

Maybe "reset initiative" could be moved. Make it an X or a refresh arrow, and put it right next to the word "init." Since the icon would be so small, make the whole word clickable. Also, don't show the icon unless there's something to reset.

After that, you'll want to think about grouping. Some buttons have to do with gameplay, and should be easily accessible. Others are mostly used for managing scenes and sessions; you could stand to put them off to the side, in a menu or something. Maybe even a collapsible menu. Here's how I would group each one:

- "Add aspect" through "add index card" - gameplay critical. Leave as-is for now. (Longer-term: consider merging "add NPC" and "add bad guy.")
- Thumbs up and thumbs down - used in gameplay, though hardly critical. Leave as-is for now. (Longer-term: could use tooltips explaining what they're for.)
- "Sort" - used in gameplay. Leave as-is for now. (Longer term: more sort options?)
- "Save scene" - scene management, but some GMs might still want to save regularly during gameplay. Put it in the scene menu, unless the menu is collapsible, in which case put it in the corner just outside the menu. (Longer-term: an auto-save option? Toggleable, of course.)
- "Load scene" - scene management. Won't come up more than a few times each session. Put it in the scene menu.
- "Reset scene" - scene management. Belongs right next to "load scene," and the only reason it isn't already is because the two were implemented at different times. (Longer-term: change to "new scene.")
- "Copy game link" - session management. Bury it deep in the menu, since normally GMs will only need to click it one time at the very beginning of a session. (Longer-term: display a temporary copy of the button when there are no players, like the copy of the "add aspect" button that shows up when there are no aspects.)

**Comment by player-03** [comment]
Hmm, this is a bunch. And also off-topic. Let me make a new issue specifically to discuss this.

**Comment by RPDeshaies** [comment]
I'll close this issue for now as the main topic as been resolved and will be part of v3.2.0
