### ISSUE TITLE
PT-BR translation

### ISSUE THREAD

**Issue by pedrogsribeiro** [fariapp/fari#109]
Hi.

This is my pt-br translation as we spoke in Reddit.
I used the licensed translation to complete this.
I must say that Fate Condensed is being translated here in Brazil so "Lore" should be "Ocultismo" but the book wasn't published yet. When it does, I can check for changes.
[pt-br.txt](https://github.com/fariapp/fari/files/5175598/pt-br.txt)

**Comment by RPDeshaies** [comment]
Will incorporate your translations this week!

**Comment by RPDeshaies** [comment]
Will be available in #113 ! Thank you so much for this!
