### ISSUE TITLE
As a GM, I want the scene UI to be simple, clear and concise 

### ISSUE THREAD

**Issue by player-03** [fariapp/fari#114]
Fari has been getting more and more great features, but with each feature comes more buttons. At some point, it gets to be too much. Here's a screenshot from an upcoming build:

![image](https://user-images.githubusercontent.com/6224111/92799852-23320480-f382-11ea-8eb0-ea9fe169a211.png)

These buttons were placed wherever there was the most room, not thinking as much about grouping. For instance, when "reset scene" was added, there was no "save scene" or "load scene," so it made sense to put it in the row that had fewer buttons. But then that row was too full for the save and load buttons, so they got their own row, separate from "reset scene." Even though if you think about it, the three buttons belong together.

I suggest splitting the buttons into two main groups: gameplay-related and scene management. Gameplay buttons are frequently used and need to be kept front and center. Management buttons are mostly used to get the session started, and don't come up as often during gameplay. It'd be totally fair to put these in a collapsible menu, off to the side.

Here are my thoughts on each individual button.

- "Add aspect" through "add index card" - gameplay critical. Leave as-is for now. (Longer-term: consider merging "add NPC" and "add bad guy.")
- Thumbs up and thumbs down - used in gameplay, though hardly critical. Leave as-is for now. (Longer-term: could use tooltips explaining what they're for.)
- "Sort" - used in gameplay. Leave as-is for now. (Longer term: more sort options?)
- "Save scene" - scene management, but some GMs might still want to save regularly during gameplay. Put it in the scene menu, unless the menu is collapsible, in which case put it in the corner just outside the menu. (Longer-term: an auto-save option? Toggleable, of course.)
- "Load scene" - scene management. Won't come up more than a few times each session. Put it in the scene menu.
- "Reset scene" - scene management. Put it in the menu. (Longer-term: change to "new scene.")
- "Copy game link" - session management. Bury it deep in the menu, since normally GMs will only need to click it one time at the very beginning of a session. (Longer-term: display a temporary copy of the button when there are no players, like the copy of the "add aspect" button that shows up when there are no aspects.)
- "Add character" - this is technically a session management button, and maybe it could go in the menu, but I also suggest putting it where "reset initiative" is now. Think of the character sheets - every time there's a button to add another of something, it's a big plus shape in the top-right of the section it adds to. That design works; why not make it standard? Just a big plus shape in the corner of the player box.
- "Reset initiative" - gameplay. Its current spot isn't terrible, but "add character" makes more sense there. The thing is, "reset initiative" isn't that important of a button, since there's another way to accomplish that. Therefore I'd make it smaller. Make it an X or a refresh arrow, and put it right next to the word "init." Then hide it unless there's something to reset.

**Comment by RPDeshaies** [comment]
I think there are some nice ideas in there so I re-arranged things a bit based on your suggestions and some personal opinions.

* I moved the add character button in the player section on the left
* I moved the reset scene at the top with the save/load buttons
* I grouped all the index card related buttons together
* changed some translation/icons to be more concise (like why repeating the word "add" everywhere instead of just using an icon)

I think I'll close this issue for now and might open a new one if we have some additional ideas in the future

Here's a preview of v3.2.0.


![image](https://user-images.githubusercontent.com/6224111/92928644-62596780-f40d-11ea-9e54-71fa51ec0590.png)

![image](https://user-images.githubusercontent.com/6224111/92928653-67b6b200-f40d-11ea-892c-a766530e187e.png)

**Comment by player-03** [comment]
The grouped buttons are great. Little bit sad to lose the unique icons, but in retrospect they were all pretty arbitrary (other than the face for the NPC). And I can't think of any better icons; aspects and boosts are so widely varied that there's literally no image that'd apply to all possibilities.

It's good to have the "save," "load," and "reset" buttons grouped, but I'm not so sure about removing the word "scene" from each of them. A new user might not be able to figure out what's being saved and loaded. My advice would be to add tooltips (if you haven't already).

"New character" button looks good.

**Comment by RPDeshaies** [comment]
Thanks for the comments, and I agree: maybe tooltips would be a good idea
