### ISSUE TITLE
French translation missing on About page

### ISSUE THREAD

**Issue by corrinachow** [fariapp/fari#115]
## 🚩 Describe the bug

French translation missing on `About` page

## 🔢 Steps to reproduce

1. Go to https://fari.app/about
2. Switch the language to `Français`
3. Page is blank

## 🟢 Expected behavior

I can view the About page in french

## 🔴 Actual behavior

About page text is missing in French

## 💅 Screenshots

...
![image](https://user-images.githubusercontent.com/35117708/93540628-4af50f80-f922-11ea-83a6-fc833f819ad2.png)

## 🖥 Desktop or Smartphone

Yes

- Browser: [e.g. chrome, safari] 

## 📄 Additional context

...

**Comment by RPDeshaies** [comment]
will be fixed in #113
