### ISSUE TITLE
Can't connect to online games

### ISSUE THREAD

**Issue by HauntedTrenchCoat** [fariapp/fari#118]
## 🚩 Describe the bug

Although it's possible for me to create games, none of my friends can connect to me or each other's games.

## 🔢 Steps to reproduce

1. Go to https://fari.app/
2. Click on "START ONLINE GAME"
3. Click on "COPY GAME LINK" and share the game
4. Whoever enters the game only see the loading animation forever

## 🟢 Expected behavior

Players being able to connect to the game after some time

## 🔴 Actual behavior

Players only see the loading animation forever

## 💅 Screenshots

![image](https://user-images.githubusercontent.com/43820923/93690050-a7833680-faaa-11ea-98ed-12985336b4c4.png)

## 🖥 Desktop or Smartphone

- Browser: [e.g. chrome, safari]

## 📄 Additional context

...

**Comment by RPDeshaies** [comment]
Hey, thanks for opening this issue, sadly there is not a lot I can personally do here but to be more transparent, I wrote a wiki page to explain the "why"

Thank you for understanding.

https://github.com/fariapp/fari/wiki/Connection-issues

**Comment by RPDeshaies** [comment]
quick question: do you know if the player that could not connect was using an ethernet connection or wifi ?

**Comment by HauntedTrenchCoat** [comment]
Thanks for answering! I think he was using ethernet connection. It also saddens me i can't use the online function of Fari... I absolutely loved the tool.

**Comment by RPDeshaies** [comment]
I heard someone saying they experienced issues with the connection of one of their players but they were able to find a work-around using a wifi connection instead. 

Do you think you could try that out since I can't reproduce it with my setup at home?
