### ISSUE TITLE
Data on Character sheets is lost.

### ISSUE THREAD

**Issue by Erynus** [fariapp/fari#119]
## 🚩 Describe the bug
On occasions stunts are lost. When you select a character sheet to join a game, part of the stunts (and occasionally all of them) are blank.

## 🔢 Steps to reproduce

1. Create a character
2. Fill the info, name and description of stunts
3. Save character sheet and/or export json
4. Load the character sheet on the same or another game.

## 🟢 Expected behavior
Text on the sheet is the one typed in

## 🔴 Actual behavior

Some or all of the stunts are blank (some times even tracks added to the sheet dissapear)

## 🖥 Desktop or Smartphone

- OS: Windows 10
- Browser: Firefox, Chrome
- Device: Pc

**Comment by RPDeshaies** [comment]
Just tried reproducing the issue on fari.app and didn't encounter any issues.

Have you experienced issues with other field types or just the `stunt` ones ?
Does it happen systematically? If not, do you have more context about how it happens ?

**Comment by Erynus** [comment]
Hi, I did more tests and it seem to happen when the text is too long. I have it happening on two sheets, one with just the third stunt description long (like 3 and a half lines) that erased all of them, and the sheet that i'm attaching that have all three descriptions long, of which just the third text dissapear.
It happens when my players join the game, but i don't know if it has to do with some issue on syncing with me  (on the first days we couldn't edit the same sheet from both ends, even taking turns, because the edits wouldn't show up. sometimes on following games, data that we put on the sheet where absent, like additional tracks for debts and resources) since once i have the sheet imported myself, it stay.

I'll keep testing. Please tell me if you coem up with something else to try.
[MARIAN 3.0.fari(1).zip](https://github.com/fariapp/fari/files/5265256/MARIAN.3.0.fari.1.zip)

**Comment by RPDeshaies** [comment]
I'll continue to do some tests on my end and with the new release i'm planning to publish but so far, even with your exported character (thanks for this) I was not able to reproduce any sync or loose of data issues but I'll keep trying.

This is something that worries me since I want to make sure Fari is as stable as it can be.
I'll keep you in the loop

**Comment by RPDeshaies** [comment]
In version 3.4 I released a much more stable sync mechanism and I hope it fixes this issue. Will close for now but dont hesitate to ask me to reopen it if it happens again
