### ISSUE TITLE
As a GM, I want to be able to import and export scenes to be able to share them with others

### ISSUE THREAD

**Issue by RyanSinger** [fariapp/fari#121]
## 🚩 Is your feature request related to a problem? Please describe
The JSON import/export function for character sheets is very useful. I'd like something similar for scenes.
...

## ✅ Describe the solution you'd like
a JSON import/export file format similar to the import/export system for characters.

**Comment by RPDeshaies** [comment]
This feature is already included in the app right now!

Just head over to fari.app, click on the "Scenes" menu: 

![image](https://user-images.githubusercontent.com/6224111/95129605-3c339880-0729-11eb-8b65-671646780017.png)

Will close this issue but don't hesitate to ask me to re-open it if I misunderstood something.
