### ISSUE TITLE
Russian localization

### ISSUE THREAD

**Issue by hattivatt** [fariapp/fari#122]
## 🚩 Is your feature request related to a problem? Please describe

No, it's new localization for Fari

## ✅ Describe the solution you'd like

I've made a Russian localization of Fari. Here is files
[fari_russian.zip](https://github.com/fariapp/fari/files/5330072/fari_russian.zip)

**Comment by RPDeshaies** [comment]
Thanks for this! I'll take a loot very soon!

**Comment by RPDeshaies** [comment]
I started the ingration, it will be part of the following release: #129

**Comment by RPDeshaies** [comment]
I have a couple of new values that would need to be translated, would you mind helping me out ?

```
  "character-dialog.dice": `Dice`,
  "character-dialog.group": `Group`,
  "play-route.fp": `F.P.`, (this one is the abbreviation for "fate points")
```

**Comment by RPDeshaies** [comment]
If you want to test your localizations: https://5f948b1f2b01497fec568b95--fari.netlify.app/?lng=ru

**Comment by hattivatt** [comment]
```
  "character-dialog.group": `Группа`,
```

For other values, I guess, I'll better take some time to think and, maybe, discuss that with local community. Is that ok?

By the way, I have noticed another new value in the testing build above. It's "Draw" in the menu. I guess, it's going to be ok to translate it as "Рисовать"

**Comment by hattivatt** [comment]
Well, after a little bit of thinking I decided it's better to leave "Dice" and "F.P." as they are. 
English word for dice is common in local RPG community and for fate points it's even more popular than variant from official translation, so "F.P." will be more recognizable.

**Comment by RPDeshaies** [comment]
Ok awesome. Thanks!
