### ISSUE TITLE
GM Draw area dark mode colours.

### ISSUE THREAD

**Issue by ddkn** [fariapp/fari#124]
## Dark mode colour contrast

Draw area has good visibility in light mode, however in dark mode the dark colour and black lines are hard to see due to blending in closely with the background.

##  Steps to reproduce

1. Click on the *Sun* or *Moon* icon in the top menu bar to toggle light/dark mode
3. Scroll down to *game draw area*
4. Squint to see it is hard to discern colours.

## Expected behavior
More visibly recognizable lines and colours.

##  Screenshots

![image](https://user-images.githubusercontent.com/13819239/95598217-0bec4280-0a26-11eb-905a-fc738695cf69.png)

![image](https://user-images.githubusercontent.com/13819239/95598249-1575aa80-0a26-11eb-8619-dd3a58b9cd83.png)

## Desktop or Smartphone
- Browser: Firefox (and likely all browsers)

## Suggestions

Ones suggestion would be to invert the line colour, and the colour of the inside of the tokens. Such that, 
* For lines: white -> black 
* For tokens: white -> dark background colour, and border is white.

~~Another might be to change the outlines to match the colour instead, however, without doing it, it is hard to determine which is the best solution.~~ That is a dumb idea.

**Comment by RPDeshaies** [comment]
You are totally right, I forgot about this. Will take a look

**Comment by ddkn** [comment]
Same, haha.

**Comment by RPDeshaies** [comment]
https://5f85aba486ab0413491d5339--fari.netlify.app/draw

Dark mode support:

![image](https://user-images.githubusercontent.com/6224111/95866136-88886500-0d35-11eb-918a-b13ead34d3d5.png)

Light mode (for comparison):

![image](https://user-images.githubusercontent.com/6224111/95866175-950cbd80-0d35-11eb-8de7-80ca948452d0.png)

**Comment by ddkn** [comment]
Looks awesome!
