### ISSUE TITLE
Missing localization

### ISSUE THREAD

**Issue by handcraftedsource** [fariapp/fari#125]
## 🚩 Describe the bug

I was curious about the preview https://github.com/fariapp/fari/discussions/123 and started the application. However, I am missing all the texts. I only see the IDs.

## 🔢 Steps to reproduce

- Open App following this link: https://5f7f725c09553e00c16ed9c9--fari.netlify.app/
- Look at the surface

## 🟢 Expected behavior

...

## 🔴 Actual behavior

...

## 💅 Screenshots

![grafik](https://user-images.githubusercontent.com/28440782/95602756-a7e17280-0a55-11eb-9418-b0ea530863b8.png)

## 🖥 Desktop or Smartphone

- OS: Win 10
- Browser: Chrome
- Device: Desktop

## 📄 Additional context
n/a

**Comment by RPDeshaies** [comment]
So it seems like there's an issue to auto-detect the right language to use from your browser.

What's the language of your browser and your OS ?

If you can, could you send me a screenshot of the values of your browsers cookies when you use Fari ?

Kind of like this:

![image](https://user-images.githubusercontent.com/6224111/95605264-b2384800-0a26-11eb-8f04-0cdc70a6abab.png)

**Comment by RPDeshaies** [comment]
I tried to fix it with some config change, can you try again here ?

https://5f80cd3c158e4b0087eff655--fari.netlify.app/

**Comment by handcraftedsource** [comment]
The changes seem to have had some effect, the texts are now visible.

For the sake of completeness: it was de-DE

![grafik](https://user-images.githubusercontent.com/28440782/95652411-0f98cb80-0af1-11eb-90dc-4ffbabd5a765.png)


Now it looks like this 👍 

![grafik](https://user-images.githubusercontent.com/28440782/95652426-27704f80-0af1-11eb-85aa-8605a36291b2.png)

**Comment by RPDeshaies** [comment]
Great!

Thanks again for opening this
Will mark as resolved
