### ISSUE TITLE
As a user, I want to easily have access to a Fate cheatsheet when I play

### ISSUE THREAD

**Issue by RPDeshaies** [fariapp/fari#126]
## 🚩 Is your feature request related to a problem? Please describe

Fate while being a relative strait forward TTRPG system, there's still a lot to know by heart and having access to a very well-designed cheat sheet during play session would be a nice addition to Fari

## ✅ Describe the solution you'd like

Inside the main navigation or inside the scene screen, we would include one or multiple buttons to have access to dialogs or notifications giving access to important piece of information.

Those important piece of information still need to be thought of since we should not include things people using Fari don't want.

E.g. a lot of people complained about the adjective ladder on Reddit so perhaps that's not something we should include

## 🤝 Collaboration

I think having a design eye to help with this project would be of a tremendous help.

Perhaps @ddkn, you would be interested in helping out or perhaps you have some ideas on how to address this issue ?

## ✏️ Describe alternatives you've considered

We could include links to already existing cheat sheets provided by evilhat, but that would force the player to leave Fari or open a new tab which is not the best experience.

**Comment by ddkn** [comment]
Yeah I can, just today is a bit cumbersome with work today. I will think about things tonight.

Perhaps a misc button or quick tips button that breaks out into more buttons, so those extra options are out of the way for most game play. E.ge inside a have a ladder button, which would have the ladder list is useful for players new to fate. Possibly the option for DM's to a list of words for the ladder they wish to use etc...

**Comment by ddkn** [comment]
So I like the idea of re-implementing the cheatsheets and required tables as a modal popup that is scroll-able for each case. By being modal it will fit a variety of screen sizes etc... with an easy access close button. Leaving the page is jarring, and possibly lead to distractions. But I take it many would just have the FCore, FCon, and FAE pdf open in a new tab anyway.

So a reference button that shows a drop down list of cheatsheets and tables to show. (FCore, Fcon, FAE detectable by the game being run)

Possibly add one for DM's to add their own for the game/scene as well, if they are running something exotic. Takes in markdown (easy), and has shortcuts for putting in fate icons as seen in the book. In the same list but as a break to identify Fari provided and GM provided things, (colours maybe?)

But as other people have pointed out, the aesthetic is the clean minimal interface, so something to adhere to.  A few simple things are nice for newcomers and expandable based on GM if they want to.

Haha, thanks for asking me to think of some things, but I do encourage others to think about some things too.

**Comment by RPDeshaies** [comment]
No stress for this, I mostly want to bounce ideas at this point. The reason I pinged you specifically was because of your design background!

> So a reference button that shows a drop down list of cheatsheets and tables to show

Yeah, something like that would be relatively easy to implement and could be very useful.

**Comment by RPDeshaies** [comment]
https://fari.app/cheat-sheet
