### ISSUE TITLE
Image paste

### ISSUE THREAD

**Issue by SpaceDiceMan** [fariapp/fari#132]
## 🚩 Is your feature request related to a problem? Please describe

Currently there is no way for the GM to share an image with the players.

## ✅ Describe the solution you'd like

It would be great if Fari would allow an (uploaded or linked) image to be shown on a (popup) card, thus setting the scene.

## ✏️ Describe alternatives you've considered

Discord allows copy/pasting of images, but requires players to swap between discord and fari, breaking the flow of the game. Also the image is no longer visible when swapping back to Fari, resulting in forgetting the details of image which might be important for the scene.

**Comment by RPDeshaies** [comment]
GMs can add images to index cards by copying the image and "CTRL + V" directly inside on the card
Players can add images to their character sheets by doing the same thing in any field of the character sheet.

See https://github.com/fariapp/fari/issues/42 for an example
