### ISSUE TITLE
Single FDice roll

### ISSUE THREAD

**Issue by SpaceDiceMan** [fariapp/fari#135]
## 🚩 Is your feature request related to a problem? Please describe

For some FATE games (eg Tachyon Squadron) as single dF needs to be rolled. Currently only 4dF is possible.

## ✅ Describe the solution you'd like

Add somewhere (eg, tabbar) a button to Roll single dF

**Comment by RPDeshaies** [comment]
This seems like an edge case but will leave open to see if this issues gets more traction.

**Comment by RPDeshaies** [comment]
Will be added in the next release
![image](https://user-images.githubusercontent.com/6224111/107421480-05f79280-6ae8-11eb-92b6-c1caba494192.png)

**Comment by RPDeshaies** [comment]
Live on fari.app ! 🥳
