### ISSUE TITLE
Full 4dF roll visible with reroll of singular dice

### ISSUE THREAD

**Issue by SpaceDiceMan** [fariapp/fari#136]
## 🚩 Is your feature request related to a problem? Please describe

Currently only total result of 4dF is visible. Some variants of FATE allow you to reroll a single dice, not all of them.

## ✅ Describe the solution you'd like

Show all 4 dF dice (as square) and their total (eg in circle). Clicking a square rerolls only that dice. Clicking circle rerolls all.

**Comment by RPDeshaies** [comment]
This seems like an edge case but will leave open to see if this issues gets more traction.
Would you mind adding which variant of Fate has that rule ?

**Comment by SpaceDiceMan** [comment]
I cant find it back...: It's a houserule for Stunts/Aspects by Fred Hicks for more gritty games.
