### ISSUE TITLE
Notes section in character sheet

### ISSUE THREAD

**Issue by SpaceDiceMan** [fariapp/fari#138]
## 🚩 Is your feature request related to a problem? Please describe

Currently there is no option to add notes (simple lines of non-bold txt) to a character sheet

## ✅ Describe the solution you'd like

Add a section to character sheets (likely under the section Refresh) where simple notes can be made.

**Comment by RPDeshaies** [comment]
Character sheets are very customisable. I would argue that you could add a new text fields in the extras sections to accomplish what you are looking for

![image](https://user-images.githubusercontent.com/6224111/97309582-97dcd780-1838-11eb-881c-05f01c7f916d.png)
