### ISSUE TITLE
Private and public tabs in the scene for GM

### ISSUE THREAD

**Issue by Senethall** [fariapp/fari#143]
## 🚩 Is your feature request related to a problem? Please describe

As a GM I would like to have some premade NPCs, aspects and Bad guys and I want to show them in a scene when their time comes. I would also like to have option to rearrange NPCs and aspects which are already in the scene.

## ✅ Describe the solution you'd like

- Divide scene into public and private tabs. Only GM can access private tab in which he can create NPCs, etc. which he can then transfer to public tab, which is scene that players see.
- allow changing position of cards in the scene by draging. (Also would be nice if you could drag and drop cards between public and private tab)

## ✏️ Describe alternatives you've considered

Other alternative would be to create NPCs and Bad Guys the same way you can create characters or scenes and then in game add option to load that NPC the same way you load scenes or characters.

**Comment by RPDeshaies** [comment]
Found a way to make a pretty good "first version" of this. It will go live in the next release!

**Comment by Senethal** [comment]
Nice! Cant wait to try it out :) Your app made my GMing days much easier, thanks for your work :)

**Comment by RPDeshaies** [comment]
It's live on https://fari.app/

Thanks again for the suggestion!
