### ISSUE TITLE
Support more than 3 columns of cards

### ISSUE THREAD

**Issue by jmicu** [fariapp/fari#144]
## 🚩 Is your feature request related to a problem? Please describe

I get frustrated when I maximize my browser window in order to view more cards at a time (without scrolling), but instead of filling the available viewport space, the cards remain locked to three columns, forcing me to scroll up and down more often to interact with the cards I need.

## ✅ Describe the solution you'd like

My ideal solution would make use of more browser "real estate" (while remaining responsive enough to narrow/collapse columns as needed, as Fari already does) by allowing more than 3 columns of cards.

## ✏️ Describe alternatives you've considered

I've seen it requested in another issue already, but I'll +1 here: the ability to rearrange (or even automatically sort!) cards would allow me to bring the most useful cards to the top, reducing the need for frequent scrolling.

(The other feature request was primarily for the ability to transfer cards back and forth between tabs, which would also help mitigate my problem, since cards that needed to persist but weren't immediately relevant could be "shelved" and brought back later.)

## 📄 Additional context

I use two 4K monitors and 2048x1536 wireless display, when running my online game for 4 player characters. Typical sessions are 3 hours. Scenes usually carry over from one session to the next; cards accumulate quickly and are often needed for multiple sessions.

Fari is only one of several apps I use to manage the game and interact with the players, so I'm always attempting to optimize my screen space (my "GM Screen").

I know almost nothing about responsive designs like this one, but I do know that many boilerplate (is that the right word?) structures are based on a grid that's then filled with elements of the designer/developer's choice. If this request were desirable for more than just me, but would require monumental effort / redesign / rebuilding, I wouldn't be surprised... just sad. 😆  Also thanks so much for your amazing work and for your responsiveness to bugs & feature requests. Fari is my favorite.

**Comment by RPDeshaies** [comment]
Thanks for opening this. I'll see what I can do for this. 

I think I would just need to tweak a couple of responsive breakpoints for some UI components so that I can support wider resolutions but I'll keep you in the loop if I encounter any blockers that would stop me from releasing that in the next release.

For now, should be able to do it for #129

**Comment by RPDeshaies** [comment]
Large displays

![image](https://user-images.githubusercontent.com/6224111/97930241-eb6b8b80-1d38-11eb-992b-b4e9eacbd5d9.png)

Medium displays

![image](https://user-images.githubusercontent.com/6224111/97930067-a5aec300-1d38-11eb-99b5-c055cac16ae9.png)

Small displays

![image](https://user-images.githubusercontent.com/6224111/97930211-d858bb80-1d38-11eb-82e2-a60397b37d63.png)
