### ISSUE TITLE
drawing area controls are not kept when switching between normal and bigger view

### ISSUE THREAD

**Issue by tgirod** [fariapp/fari#147]
## 🚩 Describe the bug

Switching between drawing area normal and bigger view resets the tools state.

## 🔢 Steps to reproduce

1. in the drawing area, select a tool other than the default one
2. click on the square to extend the drawing area
3. the selected tool is now the default one. If you switch back to regular size, it also resets to default
4. bonus: the reset also affects the "character icon" tool. It means if you add a few icons, then switch to the bigger view and keep adding icons, the icon selection will restart with the first one.

## 🟢 Expected behavior

Switching to the bigger view shouldn't affect the tools state.

**Comment by RPDeshaies** [comment]
I saw that behavior before and forgot to report a bug though you are write, it also looses the token index upon swiching from fullscreen to normal view. 

Will move the backlog.

Thanks for this

**Comment by RPDeshaies** [comment]
Will be part of the next release #129
