### ISSUE TITLE
Extras and the Fate Fractal

### ISSUE THREAD

**Issue by tgirod** [fariapp/fari#149]
## 🚩 Is your feature request related to a problem? Please describe

Sometimes it is necessary to use the fate fractal in order to describe a player extra. This would need to create a separate character sheet for the extra, but a player can only join a game with *one* character sheet.

## ✅ Describe the solution you'd like

Ideally, an extra could be either free-form text, or a complete character sheet with aspects, skills, stunts and stress tracks - the minimal character sheet template is perfect for that.

The extra UI would turn into a button in order to display the "sub-sheet".

## ✏️ Describe alternatives you've considered

Writing down everything in the free-form text of the extra.

**Comment by RPDeshaies** [comment]
Yeah you are right, having a "sub sheet" could definitely be interesting. moving to backlog

**Comment by RPDeshaies** [comment]
Will be done within https://github.com/fariapp/fari/issues/167
