### ISSUE TITLE
The game session crashes for everyone when entering with a name containing emoji

### ISSUE THREAD

**Issue by SirMarwin** [fariapp/fari#160]
## 🚩 Describe the bug

When joining a game session as a player I did enter a name followed by 🐺 emoji. The game crashed for me and others reported crashes as well.

## 🔢 Steps to reproduce

1. Go to a game link provided by GM
2. enter "Bob 🐺" as your name
3. press enter
4. The session will crash (for you as well as other connected player(s)

## 🟢 Expected behavior

When using emoji in character name, this will be displayed to everyone

## 🔴 Actual behavior

Entering emoji in character name crashes and forces reload

## 🖥 Desktop or Smartphone

- OS: Win
- Browser: Chrome and firefox

**Comment by RPDeshaies** [comment]
Woa! Good catch there! There is indeed a bug!

I found a solution, will do some testing in the next couple of days and write some tests to make sure it doesn't happen anymore

**Comment by RPDeshaies** [comment]
Will be released with #158
