### ISSUE TITLE
Map not updating for players.

### ISSUE THREAD

**Issue by CaptainDapper** [fariapp/fari#163]
## 🚩 Describe the bug

GM updates to map that don't involve new elements don't push updates to Players. Works fine when things are added or deleted though.

## 🔢 Steps to reproduce

Add something to an online game's map, have players, move the something around. Players' maps don't update...

## 🟢 Expected behavior

Map updates get sent to all players upon any change to map.

## 🔴 Actual behavior

Updates are shown to players when an element is added or removed, but not when moved around.

## 💅 Screenshots

n/a

## 🖥 Desktop or Smartphone

- OS: Windows10
- Browser: GM is on FireFix, the rest are chrome
- Device: Computer

## 📄 Additional context

:)

**Comment by RPDeshaies** [comment]
You are totally right. That is indeed a bug. Will look into it thanks

**Comment by CaptainDapper** [comment]
Great! Thanks so much :)
