### ISSUE TITLE
Two sets of skills

### ISSUE THREAD

**Issue by GabrielMPhi** [fariapp/fari#164]
## 🚩 Is your feature request related to a problem? Please describe

I would like to have the possibility to create two distinct sets of skills. 

I plan a game for Fate Part Time Gods and there are two sets of skills. Human skills and divine skills. In Fari, for now I need to add the divine skills in the normal skill list. I would like to have the ability to create a new section like the sills section, but distinct.

## ✅ Describe the solution you'd like

Have a + button to add a new section with the new skill section

## ✏️ Describe alternatives you've considered

Add the skills in the normal skill list, but with a sign that remember us that it is a divine skill. It's ok, but makes things a bit more confused.

**Comment by RPDeshaies** [comment]
Hey! Thanks for opening this.

This opens up pandoras box! In an interesting way though.

One thing I thought about was to have a way to let people have 100% control of the character sheet but this complicates the data model... a lot. 

So if for example I let people add a new "skill" section, then it would probably make sense to let them add **any type** of new sections. 

Text sections, check boxes sections and skills sections, big numbers sections (like the refresh)

This is a pretty big endeavor but it could be worth it as it could also make Fari more... friendly towards other TTRPGs like Monster of the Week or Blades in the Dark.

So to do this I see I would need to work on a couple of things:

1. Update the data model to support fully customizable sections
2. Update the UI to be able to add remove or move sections (and figure out what to do with the columns....)
3. Migrate all the characters that have been created thus far with the old model to the new one
4. Update the default "Core, Accelerated, Condensed" Templates to match the new model.

As you can imagine: it would take me a lot of time.

But I thought about playing with this for quite some time now. 

I'll add it to the backlog and probably start working on it after the next release but it will probably take me a couple of weeks / months.

**Comment by RPDeshaies** [comment]
Will close in favor of: https://github.com/fariapp/fari/issues/167
