### ISSUE TITLE
Using delete/move tools while drawing on mobile has unintended effects.

### ISSUE THREAD

**Issue by ConDar15** [fariapp/fari#170]
## 🚩 Describe the bug

When using the drawing tool on mobile if the move or delete functionality is selected the last selected drawing tool will still be active and will attempt to use perform both actions at once.

## 🔢 Steps to reproduce

1. Got to `/draw` on a mobile phone
2. Select a drawing tool (other than token placement tool, which does not appear to be affected)
3. Place down some drawings
4. Select either the delete or move tool
5. Click about on the drawing canvas and observe unusual behaviour with the previously selected tool still partially functioning. Note it is possible to use the selected functionality (delete/move) even with this unusual behaviour.

## 🟢 Expected behavior

Selecting the delete/move tools allows moving/deleting parts of the existing drawing with no additional modifications to the canvas.

## 🔴 Actual behavior

The drawing is manipulated based on the last drawing tool selected.

## 🖥 Desktop or Smartphone

- OS: Android 8.0.0
- Browser: Chrome (version 86.0.4240.198)
- Device: Motorola Moto g6 play

**Comment by RPDeshaies** [comment]
Very nice catch. Will work on a fix soon. Thanks @ConDar15
