### ISSUE TITLE
Fari loads on all devices except my chromebook

### ISSUE THREAD

**Issue by ThePolyoculi** [fariapp/fari#212]
All devices are connected to the same wifi network; phone, tablet, older laptop. Worked flawlessly on my chromebook until a few days ago, now it just loads to crash report page and then gives me the option to report the issue here.

Ideas?

**Comment by RPDeshaies** [comment]
That is very weird.

Just looked up my analytics platform and I can see your error message.

I'll investigate

![image](https://user-images.githubusercontent.com/6224111/104635466-f1061b80-566f-11eb-81ee-a217e9be4085.png)
![image](https://user-images.githubusercontent.com/6224111/104635472-f4010c00-566f-11eb-856a-c7c466ff81df.png)
![image](https://user-images.githubusercontent.com/6224111/104635507-febba100-566f-11eb-946d-6efb91c30a5a.png)

**Comment by ThePolyoculi** [comment]
It sure is! I powerwashed the chromebook in case it was a ChromeOS beta channel issue, but still the same problem. Thanks for checking in to it!

**Comment by RPDeshaies** [comment]
Seems to be related to v88 of Chrome (im on 87, downloading 88) and a framework I'm using

https://github.com/mui-org/material-ui/issues/24182

**Comment by RPDeshaies** [comment]
Yikes. Found the issue but it's a really weird one. I was able to reproduce with Chrome Canary. 

Thank you so much for finding this because this would have caused a very big outage once chrome went live with this for everyone

**Comment by RPDeshaies** [comment]
I pushed a hotfix on prod. Can you test again please @ThePolyoculi

**Comment by ThePolyoculi** [comment]
I'll be back in front of that particular Chromebook this evening and will update you then. Thanks!

**Comment by ThePolyoculi** [comment]
Success! In retrospect I should have stepped out of beta before powerwashing to isolate the issue faster. I usually keep this one in beta to test new flags and see what's on its way to stable. I'm hardly a ChromeOS power user but I know a thing or two about a thing or two. Since I'm usually in beta anyway and plan to use Fari weekly I'll let you know fast if any future versions cause snags before they move to stable.

Thanks for all you did so quickly! You're a champ!

**Comment by RPDeshaies** [comment]
Thanks for the issue! It was a tricky one to figure out but happy it didnt affect too many users!

Good luck on your next Fari session!
