### ISSUE TITLE
Large images go over bounds of aspect

### ISSUE THREAD

**Issue by Almenon** [fariapp/fari#42]
## 🚩 Describe the bug

When pasting a large image into a aspect the image goes over the bounds of the aspect

## 🔢 Steps to reproduce

1. Start new session
2. click on add aspect
3, paste in a large image

## 🟢 Expected behavior

Image is resized to fit in box and/or handles are available to resize image to fit

## 🔴 Actual behavior

Image goes over bounds of box

## 💅 Screenshots

![image](https://user-images.githubusercontent.com/13080965/82129424-88307180-9777-11ea-984e-b4fe639c94d8.png)

## 🖥 Desktop or Smartphone

- OS: Windows 10
- Browser: Chrome
- Device: Desktop

## 📄 Additional context

Workaround: resize the image to be smaller in other tab/application

**Comment by Almenon** [comment]
Nice bug format. I like the emojis.

**Comment by RPDeshaies** [comment]
@Almenon thanks for submitting the issue! (and thank you for adding all the required information) 

Well, that's definitely a feature I was not aware existed before now... 😅 

I never intended the aspect index cards to support uploading images but now that I know it already does... well might as well support that feature properly.

I've just tested a quick fix that should do the trick just fine and it should be pretty easy to fix.

**Comment by Almenon** [comment]
tested and confirmed fixed, thanks!
