### ISSUE TITLE
Be able to save a scene

### ISSUE THREAD

**Issue by ConDar15** [fariapp/fari#60]
## ✅ Describe the solution you'd like

Some way for a GM to be able to setup and save a scene beforehand. This would allow the GM to prep in advance if desired without having to do it all at the table.

## ✏️ Describe alternatives you've considered

I believe it is possible at the moment to set up multiple different simultaneous online games and get the players to switch them at the appropriate time, but this should be simplified for users.

Ideas for solutions:

- A navigation bar at the top of the GM view of an online game to swap between/create new scenes.
- A way for GMs to setup a scene offline and persist it to local storage.
- A login system for GMs/players to manage resources such as scenes/characters/etc...

## 📄 Additional context

Requested on the Fate RPG subreddit by u/Dorsai_Erynus and others: [comment requesting the feature](https://www.reddit.com/r/FATErpg/comments/go488g/fari_220_player_controls_confetti_and_dark_theme/fregu6g?utm_source=share&utm_medium=web2x)

**Comment by RPDeshaies** [comment]
I agree this would be a very nice feature. Added it in the backlog

**Comment by RPDeshaies** [comment]
This will next on my plate after release v2.3.8

**Comment by nottsknight** [comment]
If I could throw in a longer-term request to piggy-back on this one, potentially a development for further in the future could be a way of assembling multiple saved scenes into a timeline, so that you can navigate through a session?

**Comment by RPDeshaies** [comment]
FYI here's a screenshot of what I have so far for this feature.

For now, scenes will be "saved" and sorted by "last modified date" kinda thing and you will be able to load them inside a session.

Eventually, if I see people having lots and lots of scenes, I'll start thinking about more flexible grouping (per campaign?) or sorting (alphabetically?).

![image](https://user-images.githubusercontent.com/6224111/87955811-3ad4c700-ca7c-11ea-8d67-110ec2cb3a9d.png)

**Comment by RPDeshaies** [comment]
fixed in #89.
Stay tuned for the release.

FYI: I'll probably need some beta-testers in a week or two to stabilize the next version
