### ISSUE TITLE
Parts of the app not translated

### ISSUE THREAD

**Issue by Erynus** [fariapp/fari#74]
## 🚩 Is your feature request related to a problem? Please describe

About, FAQ and default values on the character sheets (careful, quick and other approach names) are not translated to spanish

## ✅ Describe the solution you'd like

Include it on the esTranslate file or point me in the right direction to the correct translation file

**Comment by RPDeshaies** [comment]
Yeah, they should be included in the list of possible translations. I will need to do some code change before we can translate them but if you have the "values" already you can include them here and I will include them as soon as the underlying infrastructure is ready!

**Comment by Erynus** [comment]
No problem. 
I would also put the about section inside the Help section, and the creator credits on the front page next to the change theme button, given that both "help" and the Github button leads to Git. And it ask for a login, so anyone without a Github account would be unable to get "help".

**Comment by RPDeshaies** [comment]
Hey, 

Since the about/faq page is stored in a markdown file and not into the standards translation files, I worked on implementing a special translation mechanism just for "markdown pages".

If you have some time and want to translate the about page, here's the original file that needs to be translated:

https://raw.githubusercontent.com/fariapp/fari/master/lib/routes/About/About.md

Thank you so much for your efforts in translating the app in Spanish, it's awesome!

**Comment by RPDeshaies** [comment]
I'll be looking into translating making the skills and approaches translatable too

**Comment by Erynus** [comment]
# Fari

Fari es una aplicación <b>Asistente para Fate RPG</b> Creada por René-Pier Deshaies-Gélinas, disponible en [Github](https://github.com/fariapp/fari) y liberada bajo [Licencia AGPL-v3](https://choosealicense.com/licenses/agpl-3.0/) .

## FAQ

### ¿ Es una aplicación Open Source ?

Si, lo es. Puedes contribuir al proyecto en [Github](https://github.com/fariapp/fari).

### ¿ Existe un changelog ?

Si, [aquí lo tienes](/changelog).

### ¿ El Lanzador de Dados es justo ?

¡Por supuesto! El Lanzador de Dados se valida cada vez que se introduce una modificación en el código, usando pruebas automatizadas que ejecutan 50.000 tiradas, para asegurar que es justo.

### ¿Donde se almacenan mis datos ?

Toda la información se guarda localmente en el dispositivo desde el que accedes a Fari
Fari no usa ninguna base de datos en la nube, pero si usamos Google Analytics

La información también se puede compartir con otros a través de conexiones peer to peer cuando se crean o se unen a partidas.
La conexión peer to peer finaliza tan pronto como se cierre la pestaña del navegador.

### Esta app mola, ¿Qué puedo hacer para ayudar?
Puedes [invitarme a un café](https://ko-fi.com/rpdeshaies) o ayudarme a construir Fari contribuyendo en [Github](https://github.com/fariapp/fari)

Trabajo en esto en mi tiempo libre y cualquier donación es enormemente apreciada. (emoji)

### ¿ Algo más ?

¡Claro! Fari no podría existir sin la ayuda de algunas maravillosas librerías y frameworks

Puedes donar para ayudarles a ellos también:
- [PeerJS](https://opencollective.com/peer) - Que te ayuda a jugar con tus amigos a través de conexiones peer to peer.

---------
My apologies for the delay

**Comment by RPDeshaies** [comment]
Thank you so much! and don't be sorry, you are helping me a ton!

**Comment by RPDeshaies** [comment]
The about section is now translated. I'll create another ticket to handle character sheet's fields
