### ISSUE TITLE
Player loose modification to their characters in the dialog when a GM syncs a scene with them

### ISSUE THREAD

**Issue by player-03** [fariapp/fari#76]
## 🚩 Describe the bug

When the GM performs any action, all other players lose unsaved data they entered into their character sheets.

## 🔢 Steps to reproduce

1. Start a game.
2. Join in a second tab, with a character sheet.
3. Open the character sheet in the second tab, and make any edit. For instance, add a physical stress box.
4. Don't save the character sheet yet.
5. In the first tab, perform any action. For instance, roll the dice.

Alternate steps with the same result:

4.5. Join in a third tab, without a character sheet.
5. In the third tab, perform any action. For instance, roll the dice.

Other edits I tested in step 2:

- Modify an aspect.
- Delete the entire skill list.
- Modify the refresh.

Other actions I tested in step 5:

- Draw a line in the drawing area.
- Create an aspect.
- Delete an aspect.
- Roll someone else's dice.
- Spend a fate point.
- Toggle whether a player has played.

## 🟢 Expected behavior

The second tab's changes are preserved, allowing them to continue editing.

## 🔴 Actual behavior

The second tab's changes are reverted to the last saved version.

## 📄 Additional context

The GM never seems to lose data, no matter how many things the other players do. (Well, the other players can save over the sheet the GM is editing, but that's different.)

**Comment by RPDeshaies** [comment]
Yeah you are totally right. Working on a fix. 

When a GM syncs a scene with the players the current logic doesn't check if the character should be updated based on "last modification date" but just always overrides it.

Very good catch and thanks for the very detailed bug

**Comment by RPDeshaies** [comment]
Fixed. Should be available on fari.app in less than 10m
