### ISSUE TITLE
Ability to resize character sheets

### ISSUE THREAD

**Issue by Dalick** [fariapp/fari#79]
## 🚩 Is your feature request related to a problem? Please describe
Currently when I am viewing a character sheet, the longer skill names wrap onto a second line. For example the skills ACADEMICS displays ACADEMI on one line and wraps the CS on the following line.

## ✅ Describe the solution you'd like

It would be nice if there was a way to resize the character sheet to make it wider so that skill names do not wrap. As it is possible to add your own custom skills, it seems like being able to manually resize the character sheet to fit the width you want would be the best option.

## ✏️ Describe alternatives you've considered

If adding the ability to resize the character sheet is too much work, then just increasing the default width of the character sheet would work as well.

## 📄 Additional context

![image](https://user-images.githubusercontent.com/22593366/84570893-31aa5900-ad5e-11ea-9d69-05d658462a10.png)

**Comment by RPDeshaies** [comment]
Thanks for filling that issue.

Could you give me some information about your screen resolution and include a screenshot that includes the entire browser, please?

I don't think I will modify the character sheet to make it re-sizeable but I want to make sure it shows properly on all devices though.

Will convert to a bug and work on some enhancements to make sure it looks nice on all resolutions but additional screenshots would be appreciated.

**Comment by Dalick** [comment]
My screen resolution is 1920x1080. I am using a Surface Pro connected to an external 1080p monitor. 

![image](https://user-images.githubusercontent.com/22593366/84596188-47855000-ae2a-11ea-86b9-636ea6003929.png)

![image](https://user-images.githubusercontent.com/22593366/84596127-ed848a80-ae29-11ea-946d-a4ccfe6dcd5b.png)

**Comment by RPDeshaies** [comment]
Thanks for the screenshots.

 I'll try to work on a more responsive character sheet soon.

It's very weird because with the same resolution I do not get the same behaviour, that being said I'll still try to fix the issue and ping you to help me test it if that's fine with you.


![image](https://user-images.githubusercontent.com/6224111/84655018-3433bc80-aede-11ea-864b-af5c205b0350.png)

**Comment by Dalick** [comment]
I would be happy to test it out if you make any changes.

**Comment by RPDeshaies** [comment]
I updated the character sheet designs and I hope that it's going to fix your issues.

I also was able to "simplify" the UI by hiding advanced features behind an "advanced mode"

![image](https://user-images.githubusercontent.com/6224111/86642501-f17b7680-bfa9-11ea-9595-d4072ede5c6e.png)

Done in #81
