### ISSUE TITLE
Button to add an index card for a zone

### ISSUE THREAD

**Issue by Dalick** [fariapp/fari#80]
## 🚩 Is your feature request related to a problem? Please describe

I would like to see a button added to the Fari play screen that is for adding a card representing a zone. Similar to the current buttons that add aspects, boosts, NPCs, etc. Clicking the Add Zone button would add an index card with a label called "Zone" and would be given a default color that is different than those in use by the other buttons (maybe yellow).

This would allow the GM to create separate cards to represent each zone that may be present in a scene, and also to just list the aspects of that zone right on the card representing the zone. It would also give a quick graphical representation to the players on what zones are available in the scene.

The added drawing tools are great for quickly sketching something out, but they do not really allow enough space (nor text) to set up the zones of a scene. Adding a button to add index cards to represent zones seems like an easy way to accomplish this.

**Comment by RPDeshaies** [comment]
The most complicated aspect of handling zones was the "drawing component" but now that it is done, creating a "zone index card" should not be complicated though I'm wondering what other people think of this.

I will gather some feedback on Reddit and see where we go from there.

Just an FYI, I initially wanted to do it that way! ahaha

**Comment by Dalick** [comment]
I ran a game yesterday using Fari (which went very well), and a situation arose where I wanted to use a countdown track. This is not something that Fari directly supports, but I just repurposed using an Aspect card for, and added several physical stress boxes to represent the countdown track. This worked fine, though it did require me explaining the players that this was a countdown track and not an aspect.

Which led me to wonder if a better option than adding an "Add Zone" button might be to add an "Add Custom" button. When clicked it would add a blank index card with no labels at all. After adding it, you could then type in your own type manually (.i.e. where it typically says Aspect, you could type Zone, Countdown, or something else that you needed at the moment). The same would hold true if you add stress boxes to the card, the boxes would not be labeled by default, but you could add a custom label if desired.

I am not sure if having the card type field be editable is easy to do, or if it would make more sense to prompt the user for a type when the click Add Custom. The same holds for allowing a custom label for stress boxes, though really just having no label used at all in these cases would also work.

I was just thinking that maybe using an Add Custom option would be useful to more people as they could use it to fit whatever unique circumstances they needed during their personal games. I know it would cover both my desire for being able to create cards for Zones as well as allowing for Countdown tracks to be used.

Anyways, I am loving the tool and I appreciate the work you have done on it. My group and I have only had a chance to use it for a couple of games now, but we already prefer it to every other method we have tried for playing Fate online.

**Comment by RPDeshaies** [comment]
> might be to add an "Add Custom" button
Added in a dev branch. Should be live in the next two weeks~

I also added a countdown track for aspects in the menu!

> My group and I have only had a chance to use it for a couple of games now, but we already prefer it to every other method we have tried for playing Fate online

This warms my heart, thank you so much!

**Comment by RPDeshaies** [comment]
linked to #81

**Comment by RPDeshaies** [comment]
Done in #81
