### ISSUE TITLE
Backspace default behavior when in character creation leads to loss of progress

### ISSUE THREAD

**Issue by mhkehrein** [fariapp/fari#90]
## 🚩 Describe the bug

...

When creating or editing a character under the "Characters" tab: If no text field is selected and backspace is pressed (such as while tabbing through icons), the default "one step back in browser history" action follows.
This usually results in being transported back to the "Scene" or "Home" tab without prompt, losing the editing progress of the character.

While this it default Browser behavior, it's very annoying. As soon as no text field is selected (be it by unfocusing a text field via clicking in "blank" space or having selected an icon (e.g. via tabbing through)), this behavior occurs and all previous changes are lost.

## 🔢 Steps to reproduce

...

1. Open app
2. Click "Characters" tab
3. Open character sheet, either via "Create New Character" and subsequent choice, or edit existing character
--> edit sheet opens
4. Edit a text field, e.g. "High Concept"
5. Click on white title bar (e.g. containing "Aspects" title)
OR
4. check "Toggle advanced mode"
5. Edit text field
6. Press "Tab" twice (so that an **icon** is focused instead of a text field
--> No text field is active
7. Press "backspace" on keyboard

## 🟢 Expected behavior

"Backspace" hit is either ignored or prompts user to accept leaving the current screen (in this case: leaving character editing mode). Alternatively: Editing progress is saved after un-focusing a text field, so that previously edited fields still contain their most current content on re-opening character editing frame.

## 🔴 Actual behavior

The user is transported back to the previous screen in the browser history. In case of reproduction steps: Home screen.

## 🖥 Desktop or Smartphone

- OS: Windows 10
- Browser: Firefox 78.0.2 (64-Bit)
- Device: n/a

**Comment by RPDeshaies** [comment]
Hey! You are totally right, this is a pretty annoying bug. I'll work on a fix in #89

**Comment by RPDeshaies** [comment]
fixed in #89 
Stay tuned for the release
