### ISSUE TITLE
Fari v3.0.0 Prerelease - Looking for Testers

### ISSUE THREAD

**Issue by RPDeshaies** [fariapp/fari#92]
Hey everyone,

In a couple of weeks, I will release the newest version of Fari: v3.0.0 (#89)

This version will include a lot of changes like:

* The ability to save scenes and load them during a play session #60 
* Better Character Management
* More control on Index Card #88 
* Exporting and Importing Scenes and Characters (Thanks @nfregoso)
* ... and even more!

Since this is a big release and it includes a lot of changes, I would like to ask the Fari community to help me test it if you have some time on your hands!

Here's a link to test the release: https://5f2dd07d2f14a5f897e2b0cc--fari.netlify.app/

I will update this link ☝️  as new features and fixes are pushed.

_Please don't report bugs or feature requests here in the comments but open new issues instead._

Thanks a lot in advance!

## ⚠️ Warning
 If you create characters or scenes in the beta website, they will not be ported over to the production site.

## Link Issues
- [x] #93 
- [x] #94

**Comment by nottsknight** [comment]
Would you like us to create separate issues for things we uncover, or comment them here?

**Comment by RPDeshaies** [comment]
@nottsknight good question. Let's create separate issues for issues with the prerelease

**Comment by RPDeshaies** [comment]
New version available: https://5f21b0946e67c5829a17b14b--fari.netlify.app/

**Comment by Erynus** [comment]
Looks pretty good!

**Comment by RPDeshaies** [comment]
@Erynus I have a couple of Spanish translation keys for you if you have some time ☺️ 

```
  "character-dialog.load-template-confirmation": `Are you sure you want to load this template and lose all your changes ?`,
  "character-dialog.load-template": `Load Template`,
 "character-dialog.template.Accelerated": `Accelerated`,
  "character-dialog.template.CoreCondensed": `Core/Condensed`,
  "character-dialog.template.Custom": `Custom`,
```

Here's the context: 

![Context](https://i.gyazo.com/4f2cdbff933145cc033eb8c5c2309470.gif)

**Comment by Erynus** [comment]
`Are you sure you want to load this template and lose all your changes ?`, =¿Está seguro de que quiere cargar esta plantilla y perder todos los cambios?
`Load Template`, = Cargar plantilla
`Accelerated`, = Acelerado
`Core/Condensed`, = Basico/Condensado
`Custom`,`= Personalizado

**Comment by RPDeshaies** [comment]
Updated.

I got a couple of others when you have the time (other I can use google translate, I feel bad for always bugging you about this)

FYI: the `{{something}}`  means something dynamic is injected in the text (like the name of the player)

```

"character-dialog.saved": `Saved`,
"index-card.add-free-invokes-track": `+ Free Invokes Track`,
"index-card.add-mental-stress-track": `+ Mental Stress Track`,
"index-card.add-physical-stress-track": `+ Physical Stress Track`,
"index-card.add-track": `+ Track`,
"manager.deleted": `Deleted`,
"manager.import": `Import`,
"manager.leave-without-saving": `Are you sure you want to leave without saving ?`,
"manager.new": `New`,
"manager.no-items": `There's nothing here yet`,
"manager.undo": `Undo`,
"menu.scenes": `Scenes`,
"play-route.join-as": `Join as ✨ {{playerName}} ✨`,
"play-route.join": `Join`,
"play-route.load-scene": `Load Scene`,
"play-route.new-scene": `New Scene`,
"play-route.save-scene": `Save Scene`,
"play-route.scene-saved": `Saved Scene`,
"player-row.has-no-character-sheet": `No Character Sheet`,
"player-row.open-character-sheet": `Open Character Sheet`,

```

**Comment by RPDeshaies** [comment]
Also: with the help of @nfregoso the latest release supports exporting and importing scenes characters!

Try it out on the new beta link: https://5f28175dc63401055d2985ee--fari.netlify.app/

**Comment by RPDeshaies** [comment]
Just finished translating the app in French (and google translated a couple of Spanish translations)
Here's another beta link: https://5f2c4ec5b96dd42592f733d2--fari.netlify.app/

I will plan on releasing v3 at the beginning of next week (there's too much traffic on the app during weekends to release a new version make the app unstable)

**Comment by RPDeshaies** [comment]
fixed a couple of things today

* infinite rendering loop when joining an online game (caused by a recent change in the DrawArea component)
* possibility to rename all labels in character sheet #101 
* possibility to reload the same scene that's currently loaded

https://5f2dd07d2f14a5f897e2b0cc--fari.netlify.app/

**Comment by RPDeshaies** [comment]
New link to handle #102 

https://5f3bf9bef5151bf7dfb6c3a1--fari.netlify.app/

**Comment by RPDeshaies** [comment]
Closing as I'm going to release v3 soon
