### ISSUE TITLE
[3.0.0 Beta] Cannot add saved characters to scenes in offline mode

### ISSUE THREAD

**Issue by nottsknight** [fariapp/fari#93]
## 🚩 Describe the bug

Saved characters cannot be added to a scene in progress in offline mode

## 🔢 Steps to reproduce

1. Create and save a new character.
2. Start an offline game.
3. Click 'Add Character'.

## 🟢 Expected behavior

Should have the option of selecting a saved character instead of just typing in a character name.

## 🔴 Actual behavior

Can only enter a name, cannot select a saved character.

## 🖥 Desktop or Smartphone

- OS: Fedora
- Browser: Firefox
- Device: PC

Have also observed this on Windows 10.

**Comment by RPDeshaies** [comment]
I actually made that on purpose because I was wondering if people in "offline mode" would be using character sheets.

I don't mind adding it back if people think it could be useful.

What do you think ?

**Comment by RPDeshaies** [comment]
Will work on a fix 
![image](https://user-images.githubusercontent.com/6224111/88719689-af011180-d0f1-11ea-9565-b2299208aed6.png)

**Comment by nottsknight** [comment]
I guess it's worth putting the option in if it's not too much work to do! Related - this doesn't seem to be an option for online games either. My use case in both situations is that I build by Big Bads as full blown characters and it'd be useful to have their full character sheet available in the game similar to the players

**Comment by RPDeshaies** [comment]
Soon scenes will be "savable" and "loadable" so that should help you out on the "big bad character sheet" section since they could be "big bad index cards" prepared in advance.

> I guess it's worth putting the option in if it's not too much work to do! 
It created other unwanted bugs so I'll need to spend a bit more time on it but nothing crazy. Thanks for the issue btw

**Comment by RPDeshaies** [comment]
Should be fixed now. 
Here's a new link: https://5f21b0946e67c5829a17b14b--fari.netlify.app/
