### ISSUE TITLE
[3.0.0 Beta] Several things

### ISSUE THREAD

**Issue by Erynus** [fariapp/fari#94]
When a scene is saved, it won't load unless you load or create another one. Like if you save a scene and push the reset button, the scene will appear empty, but the "load scene" button won't bring back the aspects. If you load or create another scene it works correctly. So you must switch to another scene for it to load properly.

Also, i don't know what i did, but when i loaded a scene and clicked in the "new" option, the whole player's panel and the load button disappeared. 
When this happens, the game closes and every player is disconnected to the "the game does not exist" screen.

I have noted that even if you change the name of the scene you overwrite the current scene, i think that changing the name should create a new scene, easing the task of creating several different scenes without needing to create a new scene everytime (given that a reset wouldn't change the scene)

Weird... whenever i joined my game and chose a character, the GM's dice suddenly rolled.
It wasn't me, because the GM screen was in a different tab. It happens whenever a new character joins and the roll is always 1 (0+-+).

The character sheet opens when you click anywhere in the character tab, not just on the "open sheet" icon.

If any player double-click on the drawing pad, the drawing is gone for him/her. It reappears when the GM adds something to the drawing.
I don't like much the double-click erase thing. It happened to me several times to need to redraw everything because of a double click, as the undo button won't undo the deletion.
I think the drawing pad rework will handle that kind of things.

For now it's all i had time to test. I'll come back to play around more.

**Comment by RPDeshaies** [comment]
Thank you for all of this:

1. For your first point there's a difference between "playing a scene" and "saving a scene you are currently playing" VS "managing your scenes" and perhaps the UI is not very clear about that
2. This is indeed a bug
3. This is, again, about the difference between "playing" or "managing your scenes". When you are in "management mode" (the scene menu in the header), you first click to create a new scene and then you can plan you things in advance and save your scenes. When you click "PLay Online", Fari creates a scene for you though it's ephemeral, so not persisted. If you click "save" it's kinda like a "backup" button. Something like "I did not create this thing in advance and my session is coming to an end so save it". I think this is a wording issue on the buttons as well as a UI issue to make the difference more clear.
4. I'll double-check the dice roll thingy
5. Opening a character sheet on the entire row is a "feature" and not a "bug". But perhaps just having the button is enough
6. Yep, that should not be possible.

Here's my todo.

- [ ] (1) Make "scene management" versus "scene session" UI more distinct
- [ ] (2) When loading a scene or a character in "Use" mode, remove the "new button"
- [ ] (4) Test weird GM dice roll when choosing a character in an online game
- [ ] (5) Remove clickable player row that can open the character sheet
- [ ] (6) Disable double click on drawing pad

**Comment by RPDeshaies** [comment]
Should be fixed now. 
Here's a new link: https://5f21b0946e67c5829a17b14b--fari.netlify.app/
