### ISSUE TITLE
Character creation missing options for Fate Varieties

### ISSUE THREAD

**Issue by nfregoso** [fariapp/fari#97]
## 🚩 Describe the bug

On the beta link, when creating characters, the options for selecting Fate Core/Condensed/Accelerated/Custom are not populating. 

## 🔢 Steps to reproduce

1. Visit beta link
2. Click on 'Characters' option in menu
3. Click on 'New' in the new popup menu
4. Click on 'Toggle Advanced Mode'
5. Note missing features

## 🟢 Expected behavior

When the 'Toggle Advanced Mode' feature is triggered, a drop down should appear to quickly update the template

## 🔴 Actual behavior

There is no dropdown option appearing

## 💅 Screenshots

...

## 🖥 Desktop or Smartphone

- OS: Windows 
- Browser: Firefox
- Device: Laptop

## 📄 Additional context

Not an issue on the current release of the site and also not an issue on the latest commit for V3 branch. Looks like just a problem on the beta link.

**Comment by RPDeshaies** [comment]
Yeah, the link in the ticket is old, I'll update it and close this ticket. Thanks!
